#include "render/gofu_render_grid_background.h"
#include "render/gofu_render_grid_liberty.h"
#include "render/gofu_render_grid_starpoint.h"
#include "render/gofu_render_stone.h"
#include "render/gofu_render_marker.h"
#include "render/gofu_render_color.h"
#include "render/gofu_render_label.h"
